\ProvidesClass{notes}

\LoadClass[12pt,a4paper]{amsart}

\RequirePackage[style=alphabetic, backend=biber, sorting=ynt]{biblatex}
\RequirePackage{amsthm,amsfonts,amsmath,amssymb,latexsym}
\RequirePackage{epsfig,graphics,color}
\RequirePackage[all]{xy}
\RequirePackage[breaklinks=true]{hyperref}
\RequirePackage{mathrsfs}
\RequirePackage{stmaryrd}
\RequirePackage{verbatim}
\RequirePackage{bm}
\RequirePackage{mathabx}
\RequirePackage{enumitem}
\RequirePackage{pgf,amsmath,tikz,type1cm,fix-cm}
\usetikzlibrary{positioning}
\RequirePackage{hyperref}

\newlength{\XHeight}
\newlength{\XWidth}
%
\setlength{\parskip}{5pt}
\setlist[itemize,1]{leftmargin=\dimexpr 26pt-.1in}

\setcounter{tocdepth}{1}


